name: CI

on:
  pull_request:
  push:
    branches: [ "master", "main"]

jobs:
  backend:
    name: Backend (Spring Boot)
    runs-on: ubuntu-latest

    services:
      postgres:
        images: postrgres:15
        env:
          POSTGRES_DB: learning_app_ci
          POSTGRES_USER: learning
          POSTGRES_PASSWORD: learning
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U donations -d donations_ci"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build + tests
        env:
          SPRING_PROFILES_ACTIVE: ci
        run: mvn -B -ntp clean verify